### ISSUE TITLE
Bad representation of the question and logic file

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/Data-Structures-And-Algorithm-Interview-Kit#15]
**Describe the bug**

Initially the Question and logic files are in txt format. Transforming all of them to .md files can help in managing them more efficiently. Go to ProblemSets/Array **_OR_** ProblemSets/Matrix. Go to any problem folder there you will find a text file which is to be converted to .md file.

**Comment by vikasganiga05** [comment]
Hi, I like to work on that

**Comment by kaiwalyakoparkar** [comment]
Actually @vikasganiga05 the ProblemSets folder is further divided into 3 parts (more to come) and these 3 parts are further divided according to the Question folders. you have to go inside every question folder and convert the Question and Logic.txt to Questions and Logic.md

**Comment by kaiwalyakoparkar** [comment]
@vikasganiga05 Would you like to work on this?

**Comment by vikasganiga05** [comment]
> @vikasganiga05 Would you like to work on this?

Yes, I will work on this

**Comment by kaiwalyakoparkar** [comment]
![SS1](https://user-images.githubusercontent.com/53310847/112257605-255b1100-8c8b-11eb-9931-01f1181ac4d3.png)

**Comment by kaiwalyakoparkar** [comment]
In the same manner, you have to go inside every folder of ProblemSet as Well as its children folders and change this file. Make sure you make different PRs for every folder. That will help me reviewing it

**Comment by vikasganiga05** [comment]
Ok, I will work on that :+1: .

**Comment by kaiwalyakoparkar** [comment]
I have assigned it to you!

**Comment by vikasganiga05** [comment]
> In the same manner, you have to go inside every folder of ProblemSet as Well as its children folders and change this file. Make sure you make different PRs for every folder. That will help me reviewing it

Every folder means, every question folder or the category folder (like Array).

**Comment by kaiwalyakoparkar** [comment]
Every question would be good. As there are many questions. Doing category-wise will make it very vast.

**Comment by kaiwalyakoparkar** [comment]
There's nothing much you have to just copy from .txt file and paste it into .md file.

**Comment by vikasganiga05** [comment]
Yeah!
The file name `Question and Logic.md` or  `README.md`

**Comment by vikasganiga05** [comment]
I will do the first PR on Array >Pproblem 1.

**Comment by kaiwalyakoparkar** [comment]
File name should be `Question and Logic.md`

**Comment by vikasganiga05** [comment]
> File name should be `Question and Logic.md`

Can I format the markdown to look good without changing the contents.

**Comment by kaiwalyakoparkar** [comment]
Yeah sure! I would love that!

**Comment by vikasganiga05** [comment]
> Yeah sure! I would love that!

I started working on it, I will finish it as soon as possible :slightly_smiling_face:

**Comment by kaiwalyakoparkar** [comment]
Take your time. :smile:

**Comment by vikasganiga05** [comment]
I opened the first PR for `Array > AlternateNegativeAndPositiveNumbers`.

**Comment by vikasganiga05** [comment]
Hi @kaiwalyakoparkar , The Array category is Done! Next i will start working on Matrix and String.
Thank You :pray:

**Comment by kaiwalyakoparkar** [comment]
Yes there are only few in matrix. In string, as I am currently working on it no need to do for it. And thank you for your time and efforts

**Comment by vikasganiga05** [comment]
> Yes there are only few in matrix. In string, as I am currently working on it no need to do for it. And thank you for your time and efforts

I never create these many PRs :sweat_smile: . It was a nice experience. So no need to work on the Matrix and String right?
Thank You :pray:

**Comment by kaiwalyakoparkar** [comment]
You can work on Matrix but not on strings

**Comment by vikasganiga05** [comment]
> You can work on Matrix but not on strings

Ok :+1:
